services:
  db:
    image: postgres:14.18
    container_name: shop_kipa_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: shop_kipa_web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/shop-kipa-app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgresql_data: